# Generated by Django 5.2.3 on 2025-07-15 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'is_active'], name='coupon_code_7591e6_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='coupon_is_acti_a018ff_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['discount_type', 'is_active'], name='coupon_discoun_443ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['current_uses', 'max_uses'], name='coupon_current_014427_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'current_uses'], name='coupon_is_acti_9fc015_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['created_at'], name='coupon_created_f46737_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_until'], name='coupon_valid_f_19425e_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user', 'used_at'], name='coupon_usag_user_id_7588f4_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'used_at'], name='coupon_usag_coupon__3ecf38_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['payment', 'coupon'], name='coupon_usag_payment_c4ef38_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['used_at', 'user'], name='coupon_usag_used_at_b80b18_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['used_at', 'coupon'], name='coupon_usag_used_at_ca226a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payment_user_id_f8d8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'created_at'], name='payment_user_id_50b433_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', 'status'], name='payment_subscri_1c7a45_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payment_stripe__4437c4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_invoice_id'], name='payment_stripe__c8c46e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'amount'], name='payment_status_9c26aa_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payment_status_271abe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'status'], name='payment_payment_cb4c74_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['billing_email'], name='payment_billing_573465_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['billing_name'], name='payment_billing_6837ef_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at', 'user'], name='payment_created_840678_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at', 'user'], name='payment_paid_at_37ac14_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['updated_at', 'user'], name='payment_updated_0b6a63_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['plan_type', 'is_active'], name='subscriptio_plan_ty_ee24db_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['billing_cycle', 'is_active'], name='subscriptio_billing_0fcb68_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['price_monthly', 'is_active'], name='subscriptio_price_m_c2a585_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['price_yearly', 'is_active'], name='subscriptio_price_y_362f76_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['charts_per_month', 'is_active'], name='subscriptio_charts__7e6e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['ai_interpretations_per_month', 'is_active'], name='subscriptio_ai_inte_033416_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['priority_support', 'is_active'], name='subscriptio_priorit_a6d384_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_popular', 'is_active'], name='subscriptio_is_popu_119828_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_active', 'created_at'], name='subscriptio_is_acti_9647d8_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='user_subscr_user_id_76d59b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'plan'], name='user_subscr_user_id_86ab74_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'current_period_end'], name='user_subscr_status_65db8c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['stripe_customer_id'], name='user_subscr_stripe__11bae0_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['stripe_subscription_id'], name='user_subscr_stripe__512dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'last_usage_reset'], name='user_subscr_user_id_ea5df6_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['charts_used_this_month', 'interpretations_used_this_month'], name='user_subscr_charts__f2a9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['created_at', 'user'], name='user_subscr_created_db4d62_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['updated_at', 'user'], name='user_subscr_updated_163a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['current_period_start', 'current_period_end'], name='user_subscr_current_117a48_idx'),
        ),
    ]
