import os


def theme_context(request):

    THEME_NAMES = [
        "Standard", "Abyssal", "Spiral", "Found Footage", "Seaside",
        "Retro (Dark)", "Retro (Light)", "LED", "Uncanny Black", "Neo-80s",
        "Monolith", "Casie", "Flesh", "Ripper", "Archives", "Shrouded",
        "Alarm", "Wood", "Honey", "Jaguar", "Hills", "Film", "Mythos",
        "Tide I", "Tides II", "XNX", "Grimoire", "Clue", "Shiba", "Seaweed",
        "Moldy Black", "Attic", "Kinda Black", "Old Print", "Deep Gold",
        "Omen", "Neon Slasher", "Gothic", "ZR", "Faraday", "Iron Rain",
        "Palm Trees", "Blood Dawn", "Samhain", "Riverside Incident",
        "Backrooms", "Mondo", "Bloodlord", "Skeletal King", "Swamp Snarl",
        "Faded Pumpkin", "Haircuts", "Tarocco", "Gardener", "Seville",
        "Watercolor", "Leatherface", "Caution Tape", "Cherry Candy",
        "Occulatation", "Cursed Slab", "Marsh", "Apple Pie", "Fish", "Copper",
        "Ciemna Czekolada", "Sweet Dreams", "Family Crypt", "Empty Church",
        "Cotton Candy", "Shelter", "199X", "PAL1"
    ]

    # Define custom palettes here
    PALETTES = {
        "PAL1": {
            "primary": "#2d203a",
            "secondary": "#483d5a",
            "accent": "#76b4bd",
            "accent_secondary": "#8ad0d9",
            "text_primary": "#FFF1E8",
            "text_secondary": "#dcd5d0",
            "text_muted": "#a6a09c",
            "border": "#346a71",
            "border_light": "#4d8a91",
        },
        "Standard": {
            "primary": "#0a0a0a",
            "secondary": "#1c1c1c",
            "accent": "#FFFFFF",
            "accent_secondary": "#e5e5e5",
            "text_primary": "#f0f0f0",
            "text_secondary": "#b2b2b2",
            "text_muted": "#888888",
            "border": "#333333",
            "border_light": "#cccccc",
        },
        "Abyssal": {
            "primary": "#1a131a",
            "secondary": "#3f2a33",
            "accent": "#fdeec9",
            "accent_secondary": "#ac8b70",
            "text_primary": "#fdeec9",
            "text_secondary": "#d9cbb0",
            "text_muted": "#b6a897",
            "border": "#5f4b50",
            "border_light": "#fdeec9",
        },
        "Spiral": {
            "primary": "#20273d",
            "secondary": "#353c50",
            "accent": "#eef0f5",
            "accent_secondary": "#a2a6b1",
            "text_primary": "#eef0f5",
            "text_secondary": "#c8cdd6",
            "text_muted": "#a2a6b1",
            "border": "#555c70",
            "border_light": "#eef0f5",
        },
        "Found Footage": {
            "primary": "#2f201d",
            "secondary": "#5a4743",
            "accent": "#e6d5d2",
            "accent_secondary": "#f0e9e7",
            "text_primary": "#e6d5d2",
            "text_secondary": "#d1bfbc",
            "text_muted": "#bcaead",
            "border": "#e6d5d2",
            "border_light": "#f0e9e7",
        },
        "Seaside": {
            "primary": "#4b7d9e",
            "secondary": "#6da2c8",
            "accent": "#fef4b5",
            "accent_secondary": "#fff8c2",
            "text_primary": "#fef4b5",
            "text_secondary": "#dcd5a0",
            "text_muted": "#a5aeb8",
            "border": "#fef4b5",
            "border_light": "#fff8c2",
        },
        "Retro (Dark)": {
            "primary": "#101d00",
            "secondary": "#2c4800",
            "accent": "#98e23a",
            "accent_secondary": "#b0f05a",
            "text_primary": "#98e23a",
            "text_secondary": "#78b42f",
            "text_muted": "#5a8a23",
            "border": "#4c6820",
            "border_light": "#b0f05a",
        },
        "Retro (Light)": {
            "primary": "#eff0c1",
            "secondary": "#e0e2a8",
            "accent": "#4a5442",
            "accent_secondary": "#636e5a",
            "text_primary": "#4a5442",
            "text_secondary": "#636e5a",
            "text_muted": "#848e7c",
            "border": "#4a5442",
            "border_light": "#636e5a",
        },
        "LED": {
            "primary": "#1a182c",
            "secondary": "#2c2a3e",
            "accent": "#ffffff",
            "accent_secondary": "#f0f0f0",
            "text_primary": "#ffffff",
            "text_secondary": "#d0d0d0",
            "text_muted": "#a0a0a0",
            "border": "#ffffff",
            "border_light": "#f0f0f0",
        },
        "Uncanny Black": {
            "primary": "#0a0a0f",
            "secondary": "#1c1c24",
            "accent": "#ebebff",
            "accent_secondary": "#8c8d99",
            "text_primary": "#ebebff",
            "text_secondary": "#babbc7",
            "text_muted": "#8c8d99",
            "border": "#4c4c5e",
            "border_light": "#d6d8ff",
        },
        "Neo-80s": {
            "primary": "#1e0033",
            "secondary": "#3c016d",
            "accent": "#d86ee5",
            "accent_secondary": "#f1d8f7",
            "text_primary": "#f1d8f7",
            "text_secondary": "#d86ee5",
            "text_muted": "#aa5fb7",
            "border": "#7a2fa5",
            "border_light": "#f1d8f7",
        },
        "Monolith": {
            "primary": "#100000",
            "secondary": "#2d2a28",
            "accent": "#e50914",
            "accent_secondary": "#f25a61",
            "text_primary": "#f0f0f0",
            "text_secondary": "#e50914",
            "text_muted": "#89050c",
            "border": "#89050c",
            "border_light": "#f25a61",
        },
        "Casie": {
            "primary": "#4a5462",
            "secondary": "#636e7a",
            "accent": "#f0e9dd",
            "accent_secondary": "#f8f4ed",
            "text_primary": "#f0e9dd",
            "text_secondary": "#d1ccc3",
            "text_muted": "#89919b",
            "border": "#f0e9dd",
            "border_light": "#f8f4ed",
        },
        "Flesh": {
            "primary": "#4a4453",
            "secondary": "#635e6b",
            "accent": "#f3b8b8",
            "accent_secondary": "#f8dcdc",
            "text_primary": "#f3b8b8",
            "text_secondary": "#d6a2a2",
            "text_muted": "#91899a",
            "border": "#f3b8b8",
            "border_light": "#f8dcdc",
        },
        "Ripper": {
            "primary": "#1a0513",
            "secondary": "#2c0a21",
            "accent": "#ff009d",
            "accent_secondary": "#ff4dc4",
            "text_primary": "#f0f0f0",
            "text_secondary": "#ff009d",
            "text_muted": "#b3006e",
            "border": "#b3006e",
            "border_light": "#ff4dc4",
        },
        "Archives": {
            "primary": "#2a2823",
            "secondary": "#3c3933",
            "accent": "#e5dcc9",
            "accent_secondary": "#f2eadf",
            "text_primary": "#e5dcc9",
            "text_secondary": "#c9c0b0",
            "text_muted": "#6c6861",
            "border": "#e5dcc9",
            "border_light": "#f2eadf",
        },
        "Shrouded": {
            "primary": "#0f1a10",
            "secondary": "#1c2a1e",
            "accent": "#d2d88c",
            "accent_secondary": "#e6ebaa",
            "text_primary": "#d2d88c",
            "text_secondary": "#b6bc79",
            "text_muted": "#3d4a3e",
            "border": "#d2d88c",
            "border_light": "#e6ebaa",
        },
        "Alarm": {
            "primary": "#0a0a0a",
            "secondary": "#1c1c1c",
            "accent": "#ff0000",
            "accent_secondary": "#ff3b3b",
            "text_primary": "#f0f0f0",
            "text_secondary": "#ff0000",
            "text_muted": "#b30000",
            "border": "#b30000",
            "border_light": "#ff3b3b",
        },
        "Wood": {
            "primary": "#6e4a3a",
            "secondary": "#8a6d5a",
            "accent": "#e6d5b8",
            "accent_secondary": "#f0e5c9",
            "text_primary": "#e6d5b8",
            "text_secondary": "#d1bf9f",
            "text_muted": "#a48a74",
            "border": "#e6d5b8",
            "border_light": "#f0e5c9",
        },
        "Honey": {
            "primary": "#2a1d0a",
            "secondary": "#4d3c1a",
            "accent": "#ffb400",
            "accent_secondary": "#ffca4d",
            "text_primary": "#ffb400",
            "text_secondary": "#e0a000",
            "text_muted": "#8a785a",
            "border": "#ffb400",
            "border_light": "#ffca4d",
        },
        "Jaguar": {
            "primary": "#000000",
            "secondary": "#1c1c1c",
            "accent": "#00ffff",
            "accent_secondary": "#d88dff",
            "text_primary": "#ffffff",
            "text_secondary": "#d88dff",
            "text_muted": "#b36bff",
            "border": "#333333",
            "border_light": "#d88dff",
        },
        "Hills": {
            "primary": "#3d3a39",
            "secondary": "#5a5655",
            "accent": "#cac5c1",
            "accent_secondary": "#e0dcd9",
            "text_primary": "#cac5c1",
            "text_secondary": "#b1aca8",
            "text_muted": "#7e7977",
            "border": "#cac5c1",
            "border_light": "#e0dcd9",
        },
        "Film": {
            "primary": "#3a2f2c",
            "secondary": "#5e4d48",
            "accent": "#dcbfa9",
            "accent_secondary": "#e9d5c6",
            "text_primary": "#dcbfa9",
            "text_secondary": "#c3a995",
            "text_muted": "#8a7d78",
            "border": "#dcbfa9",
            "border_light": "#e9d5c6",
        },
        "Mythos": {
            "primary": "#1e2a22",
            "secondary": "#33473b",
            "accent": "#a0e0b0",
            "accent_secondary": "#c0f0d0",
            "text_primary": "#a0e0b0",
            "text_secondary": "#80c090",
            "text_muted": "#4a5e52",
            "border": "#a0e0b0",
            "border_light": "#c0f0d0",
        },
        "Tide I": {
            "primary": "#222034",
            "secondary": "#302e4d",
            "accent": "#8c88b8",
            "accent_secondary": "#a9a4d9",
            "text_primary": "#a9a4d9",
            "text_secondary": "#8c88b8",
            "text_muted": "#565275",
            "border": "#a9a4d9",
            "border_light": "#c0bcdc",
        },
        "Tides II": {
            "primary": "#0a1429",
            "secondary": "#1e2943",
            "accent": "#a0adc4",
            "accent_secondary": "#b8c2d4",
            "text_primary": "#a0adc4",
            "text_secondary": "#8592a8",
            "text_muted": "#4a5568",
            "border": "#4a5568",
            "border_light": "#b8c2d4",
        },
        "XNX": {
            "primary": "#222f4b",
            "secondary": "#384564",
            "accent": "#f1f3e8",
            "accent_secondary": "#ffffff",
            "text_primary": "#f1f3e8",
            "text_secondary": "#c9ccd8",
            "text_muted": "#606984",
            "border": "#f1f3e8",
            "border_light": "#ffffff",
        },
        "Grimoire": {
            "primary": "#1a100a",
            "secondary": "#33281f",
            "accent": "#d9c8a9",
            "accent_secondary": "#e6dcc6",
            "text_primary": "#d9c8a9",
            "text_secondary": "#bdae93",
            "text_muted": "#5a4d43",
            "border": "#d9c8a9",
            "border_light": "#e6dcc6",
        },
        "Clue": {
            "primary": "#2b1f1e",
            "secondary": "#40302d",
            "accent": "#f1e6e4",
            "accent_secondary": "#f8f2f1",
            "text_primary": "#f1e6e4",
            "text_secondary": "#d3c8c6",
            "text_muted": "#6b5a58",
            "border": "#f1e6e4",
            "border_light": "#f8f2f1",
        },
        "Shiba": {
            "primary": "#1f2e1a",
            "secondary": "#495a43",
            "accent": "#f8f2e7",
            "accent_secondary": "#e6b99d",
            "text_primary": "#f8f2e7",
            "text_secondary": "#e6b99d",
            "text_muted": "#495a43",
            "border": "#f8f2e7",
            "border_light": "#ffffff",
        },
        "Seaweed": {
            "primary": "#192c2b",
            "secondary": "#304443",
            "accent": "#c4e5e1",
            "accent_secondary": "#d9f2ef",
            "text_primary": "#c4e5e1",
            "text_secondary": "#a9c8c4",
            "text_muted": "#5e7371",
            "border": "#c4e5e1",
            "border_light": "#d9f2ef",
        },
        "Moldy Black": {
            "primary": "#1a1d1a",
            "secondary": "#2c312c",
            "accent": "#d4dcd4",
            "accent_secondary": "#e8ebe8",
            "text_primary": "#d4dcd4",
            "text_secondary": "#b8c0b8",
            "text_muted": "#5c615c",
            "border": "#d4dcd4",
            "border_light": "#e8ebe8",
        },
        "Attic": {
            "primary": "#3d3531",
            "secondary": "#5a504b",
            "accent": "#d4c8c1",
            "accent_secondary": "#e8e0db",
            "text_primary": "#d4c8c1",
            "text_secondary": "#b8b0ab",
            "text_muted": "#7a726d",
            "border": "#d4c8c1",
            "border_light": "#e8e0db",
        },
        "Kinda Black": {
            "primary": "#2a282e",
            "secondary": "#3c3941",
            "accent": "#d4d2d9",
            "accent_secondary": "#e8e7eb",
            "text_primary": "#d4d2d9",
            "text_secondary": "#b8b6bc",
            "text_muted": "#6c6a71",
            "border": "#d4d2d9",
            "border_light": "#e8e7eb",
        },
        "Old Print": {
            "primary": "#231c17",
            "secondary": "#3d322b",
            "accent": "#a88d7a",
            "accent_secondary": "#c1a897",
            "text_primary": "#a88d7a",
            "text_secondary": "#8e7668",
            "text_muted": "#54483f",
            "border": "#a88d7a",
            "border_light": "#c1a897",
        },
        "Deep Gold": {
            "primary": "#3a2d0a",
            "secondary": "#5e4a1a",
            "accent": "#9abf3a",
            "accent_secondary": "#e6dd8f",
            "text_primary": "#e6dd8f",
            "text_secondary": "#9abf3a",
            "text_muted": "#5e4a1a",
            "border": "#e6dd8f",
            "border_light": "#ffffff",
        },
        "Omen": {
            "primary": "#2f2d3b",
            "secondary": "#4f4b68",
            "accent": "#f6c49c",
            "accent_secondary": "#e55e5e",
            "text_primary": "#f6c49c",
            "text_secondary": "#e55e5e",
            "text_muted": "#4f4b68",
            "border": "#f6c49c",
            "border_light": "#ffffff",
        },
        "Neon Slasher": {
            "primary": "#000000",
            "secondary": "#1c1c1c",
            "accent": "#FFFF00",
            "accent_secondary": "#00FF00",
            "text_primary": "#FFFFFF",
            "text_secondary": "#00FF00",
            "text_muted": "#0000FF",
            "border": "#FF00FF",
            "border_light": "#00FFFF",
        },
        "Gothic": {
            "primary": "#2c2c2c",
            "secondary": "#3c3c3c",
            "accent": "#9e2828",
            "accent_secondary": "#c8c8b8",
            "text_primary": "#c8c8b8",
            "text_secondary": "#9e2828",
            "text_muted": "#828278",
            "border": "#828278",
            "border_light": "#c8c8b8",
        },
        "ZR": {
            "primary": "#000000",
            "secondary": "#2525a5",
            "accent": "#f2f294",
            "accent_secondary": "#dca57d",
            "text_primary": "#f2f294",
            "text_secondary": "#7d7df2",
            "text_muted": "#dca57d",
            "border": "#7d7df2",
            "border_light": "#f2f294",
        },
        "Faraday": {
            "primary": "#131313",
            "secondary": "#3c3c3c",
            "accent": "#d48f6a",
            "accent_secondary": "#b4d4b4",
            "text_primary": "#b4d4b4",
            "text_secondary": "#d48f6a",
            "text_muted": "#8c4b3f",
            "border": "#8c4b3f",
            "border_light": "#d48f6a",
        },
        "Iron Rain": {
            "primary": "#3b181f",
            "secondary": "#432d53",
            "accent": "#954c38",
            "background": "#3b181f",
            "text": "#d7a593",
            "text_accent": "#954c38",
            "border": "#d7a593",
            "link": "#954c38",
            "link_hover": "#d7a593",
            "success": "#d7a593",
            "error": "#954c38",
            "info": "#432d53",
            "warning": "#954c38"
        },
        "Palm Trees": {
            "primary": "#1f7373",
            "secondary": "#53a5a5",
            "accent": "#f2b4d4",
            "background": "#53a5a5",
            "text": "#f2b4d4",
            "text_accent": "#b4d4f2",
            "border": "#b4d4f2",
            "link": "#f2b4d4",
            "link_hover": "#b4d4f2",
            "success": "#b4d4f2",
            "error": "#f2b4d4",
            "info": "#1f7373",
            "warning": "#f2b4d4"
        },
        "Blood Dawn": {
            "primary": "#181c28",
            "secondary": "#442c2c",
            "accent": "#943c3c",
            "accent_secondary": "#8494a4",
            "text_primary": "#8494a4",
            "text_secondary": "#943c3c",
            "text_muted": "#4a5568",
            "border": "#8494a4",
            "border_light": "#943c3c",
        },
        "Samhain": {
            "primary": "#43132d",
            "secondary": "#9e3c9e",
            "accent": "#d3738c",
            "background": "#131313",
            "text": "#f28cb4",
            "text_accent": "#d3738c",
            "border": "#d3738c",
            "link": "#d3738c",
            "link_hover": "#f28cb4",
            "success": "#f28cb4",
            "error": "#d3738c",
            "info": "#9e3c9e",
            "warning": "#d3738c"
        },
        "Riverside Incident": {
            "primary": "#23282e",
            "secondary": "#2e3a4e",
            "accent": "#7a585d",
            "background": "#23282e",
            "text": "#a4b8c8",
            "text_accent": "#a4b8c8",
            "border": "#a4b8c8",
            "link": "#7a585d",
            "link_hover": "#a4b8c8",
            "success": "#a4b8c8",
            "error": "#7a585d",
            "info": "#2e3a4e",
            "warning": "#7a585d"
        },
        "Backrooms": {
            "primary": "#2d2d35",
            "secondary": "#4e4e58",
            "accent": "#d7d7a2",
            "accent_secondary": "#7c6b41",
            "text_primary": "#d7d7a2",
            "text_secondary": "#a5a582",
            "text_muted": "#7c6b41",
            "border": "#7c6b41",
            "border_light": "#d7d7a2",
        },
        "Mondo": {
            "primary": "#202a28",
            "secondary": "#373d33",
            "accent": "#a13426",
            "accent_secondary": "#f0e4b3",
            "text_primary": "#f0e4b3",
            "text_secondary": "#a13426",
            "text_muted": "#60685b",
            "border": "#60685b",
            "border_light": "#f0e4b3",
        },
        "Bloodlord": {
            "primary": "#1c0000",
            "secondary": "#4a0000",
            "accent": "#980404",
            "accent_secondary": "#4a535a",
            "text_primary": "#e0e0e0",
            "text_secondary": "#980404",
            "text_muted": "#5f0000",
            "border": "#4a535a",
            "border_light": "#980404",
        },
        "Skeletal King": {
            "primary": "#000000",
            "secondary": "#080c13",
            "accent": "#b0f1f2",
            "accent_secondary": "#ffffff",
            "text_primary": "#eefefd",
            "text_secondary": "#b0f1f2",
            "text_muted": "#3a4151",
            "border": "#3a4151",
            "border_light": "#b0f1f2",
        },
        "Swamp Snarl": {
            "primary": "#252b1e",
            "secondary": "#414a32",
            "accent": "#8e8631",
            "accent_secondary": "#a59d48",
            "text_primary": "#8e8631",
            "text_secondary": "#5a6256",
            "text_muted": "#414a32",
            "border": "#5a6256",
            "border_light": "#8e8631",
        },
        "Faded Pumpkin": {
            "primary": "#28181c",
            "secondary": "#4b323b",
            "accent": "#d6a593",
            "accent_secondary": "#c09484",
            "text_primary": "#f0e2da",
            "text_secondary": "#d6a593",
            "text_muted": "#6c4a51",
            "border": "#6c4a51",
            "border_light": "#d6a593",
        },
        "Haircuts": {
            "primary": "#1f1e00",
            "secondary": "#005f9e",
            "accent": "#299bff",
            "accent_secondary": "#e8d414",
            "text_primary": "#f0f0f0",
            "text_secondary": "#299bff",
            "text_muted": "#b13e20",
            "border": "#005f9e",
            "border_light": "#299bff",
        },
        "Tarocco": {
            "primary": "#001330",
            "secondary": "#002d57",
            "accent": "#fca37a",
            "accent_secondary": "#d6615a",
            "text_primary": "#f0f0f0",
            "text_secondary": "#fca37a",
            "text_muted": "#d6615a",
            "border": "#002d57",
            "border_light": "#fca37a",
        },
        "Gardener": {
            "primary": "#251822",
            "secondary": "#482d45",
            "accent": "#c1c873",
            "accent_secondary": "#d1d88a",
            "text_primary": "#c1c873",
            "text_secondary": "#6e7955",
            "text_muted": "#482d45",
            "border": "#6e7955",
            "border_light": "#c1c873",
        },
        "Seville": {
            "primary": "#283538",
            "secondary": "#243f43",
            "accent": "#e3d36e",
            "accent_secondary": "#f0e691",
            "text_primary": "#e3d36e",
            "text_secondary": "#4b787c",
            "text_muted": "#243f43",
            "border": "#4b787c",
            "border_light": "#e3d36e",
        },
        "Watercolor": {
            "primary": "#5e5362",
            "secondary": "#a0a9b2",
            "accent": "#f5ba8a",
            "accent_secondary": "#c38073",
            "text_primary": "#f5ba8a",
            "text_secondary": "#c38073",
            "text_muted": "#a0a9b2",
            "border": "#a0a9b2",
            "border_light": "#f5ba8a",
        },
        "Leatherface": {
            "primary": "#3a354a",
            "secondary": "#635e6b",
            "accent": "#e4beac",
            "accent_secondary": "#f0d1c4",
            "text_primary": "#f5ede9",
            "text_secondary": "#e4beac",
            "text_muted": "#85858b",
            "border": "#85858b",
            "border_light": "#e4beac",
        },
        "Caution Tape": {
            "primary": "#2a2720",
            "secondary": "#675c23",
            "accent": "#d3a518",
            "accent_secondary": "#e0b83a",
            "text_primary": "#f0e0b4",
            "text_secondary": "#d3a518",
            "text_muted": "#a0905e",
            "border": "#675c23",
            "border_light": "#f0e0b4",
        },
        "Cherry Candy": {
            "primary": "#55143b",
            "secondary": "#75345b",
            "accent": "#de4587",
            "accent_secondary": "#e86aaa",
            "text_primary": "#f5d4e6",
            "text_secondary": "#de4587",
            "text_muted": "#ae6ca3",
            "border": "#ae6ca3",
            "border_light": "#f5d4e6",
        },
        "Occulatation": {
            "primary": "#2f2d4f",
            "secondary": "#4f4b68",
            "accent": "#e55e5e",
            "accent_secondary": "#f6c49c",
            "text_primary": "#f6c49c",
            "text_secondary": "#e55e5e",
            "text_muted": "#8d8aad",
            "border": "#4f4b68",
            "border_light": "#f6c49c",
        },
        "Cursed Slab": {
            "primary": "#40415a",
            "secondary": "#60617a",
            "accent": "#9e6b4d",
            "accent_secondary": "#e5aa91",
            "text_primary": "#e5aa91",
            "text_secondary": "#a8a49c",
            "text_muted": "#9e6b4d",
            "border": "#a8a49c",
            "border_light": "#e5aa91",
        },
        "Marsh": {
            "primary": "#394a36",
            "secondary": "#637460",
            "accent": "#978364",
            "accent_secondary": "#a99475",
            "text_primary": "#978364",
            "text_secondary": "#93a38b",
            "text_muted": "#637460",
            "border": "#637460",
            "border_light": "#978364",
        },
        "Apple Pie": {
            "primary": "#4c444c",
            "secondary": "#eee8d8",
            "accent": "#6985a1",
            "accent_secondary": "#d78585",
            "text_primary": "#eee8d8",
            "text_secondary": "#d78585",
            "text_muted": "#6985a1",
            "border": "#eee8d8",
            "border_light": "#ffffff",
        },
        "Fish": {
            "primary": "#4d6a4b",
            "secondary": "#829d7f",
            "accent": "#ada98b",
            "accent_secondary": "#c2be9f",
            "text_primary": "#d5e4d1",
            "text_secondary": "#ada98b",
            "text_muted": "#829d7f",
            "border": "#829d7f",
            "border_light": "#d5e4d1",
        },
        "Copper": {
            "primary": "#393444",
            "secondary": "#2e756c",
            "accent": "#b2745a",
            "accent_secondary": "#b15a3a",
            "text_primary": "#b2745a",
            "text_secondary": "#b15a3a",
            "text_muted": "#2e756c",
            "border": "#2e756c",
            "border_light": "#b2745a",
        },
        "Ciemna Czekolada": {
            "primary": "#0f0d0b",
            "secondary": "#2d2d2d",
            "accent": "#caac8e",
            "accent_secondary": "#a5602a",
            "text_primary": "#caac8e",
            "text_secondary": "#a5602a",
            "text_muted": "#2d2d2d",
            "border": "#2d2d2d",
            "border_light": "#caac8e",
        },
        "Sweet Dreams": {
            "primary": "#586a6a",
            "secondary": "#738173",
            "accent": "#d3e5ea",
            "accent_secondary": "#bab4d3",
            "text_primary": "#f0f5f5",
            "text_secondary": "#d3e5ea",
            "text_muted": "#9993b3",
            "border": "#9993b3",
            "border_light": "#d3e5ea",
        },
        "Family Crypt": {
            "primary": "#353d34",
            "secondary": "#566255",
            "accent": "#dcb394",
            "accent_secondary": "#e6c7ad",
            "text_primary": "#f0f2ef",
            "text_secondary": "#d5e2d2",
            "text_muted": "#8a968a",
            "border": "#566255",
            "border_light": "#d5e2d2",
        },
        "Empty Church": {
            "primary": "#333d37",
            "secondary": "#535d57",
            "accent": "#d4d3d8",
            "accent_secondary": "#b2928c",
            "text_primary": "#f0f0f0",
            "text_secondary": "#d4d3d8",
            "text_muted": "#756f6c",
            "border": "#756f6c",
            "border_light": "#d4d3d8",
        },
        "Cotton Candy": {
            "primary": "#52557e",
            "secondary": "#7a81ab",
            "accent": "#f4edc2",
            "accent_secondary": "#f4acba",
            "text_primary": "#f4edc2",
            "text_secondary": "#f4acba",
            "text_muted": "#7a81ab",
            "border": "#7a81ab",
            "border_light": "#f4edc2",
        },
        "Shelter": {
            "primary": "#594c58",
            "secondary": "#8d8058",
            "accent": "#f0e39c",
            "accent_secondary": "#d8a26b",
            "text_primary": "#f0e39c",
            "text_secondary": "#d8a26b",
            "text_muted": "#8d8058",
            "border": "#8d8058",
            "border_light": "#f0e39c",
        },
        "199X": {
            "primary": "#454050",
            "secondary": "#60393f",
            "accent": "#c9be9f",
            "accent_secondary": "#537e6f",
            "text_primary": "#c9be9f",
            "text_secondary": "#537e6f",
            "text_muted": "#60393f",
            "border": "#60393f",
            "border_light": "#c9be9f",
        },
    }

    PLACEHOLDER_COLORS = {
        "primary": "#000000",
        "secondary": "#111111",
        "accent": "#ff00ff",
        "accent_secondary": "#ff88ff",
        "text_primary": "#ffffff",
        "text_secondary": "#eeeeee",
        "text_muted": "#cccccc",
        "border": "#333333",
        "border_light": "#444444",
    }

    THEMES = []
    for theme_name in THEME_NAMES:
        THEMES.append({
            "name": theme_name,
            "slug": theme_name.lower().replace(" ", "-").replace("(", "").replace(")", ""),
            "colors": PALETTES.get(theme_name, PLACEHOLDER_COLORS),
        })

    current_theme_slug = request.session.get('user_theme', 'standard')  # default theme

    return {
        'THEMES': THEMES,
        'current_theme_slug': current_theme_slug,
    }
