# Generated by Django 5.2.3 on 2025-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['user', 'created_at'], name='chart_user_id_5ba866_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['user', 'is_favorite', 'created_at'], name='chart_user_id_88a791_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['user', 'zodiac_type', 'house_system'], name='chart_user_id_64b128_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['birth_date', 'birth_time'], name='chart_birth_d_24ff65_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['latitude', 'longitude'], name='chart_latitud_ed620a_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['is_public'], name='chart_is_publ_045d52_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['is_favorite'], name='chart_is_favo_a17936_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['zodiac_type', 'house_system'], name='chart_zodiac__e8dc22_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['planetary_positions'], name='idx_chart_planetary_positions'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['house_positions'], name='idx_chart_house_positions'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['aspects'], name='idx_chart_aspects'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['created_at', 'user'], name='chart_created_6350e5_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['updated_at', 'user'], name='chart_updated_b5127e_idx'),
        ),
    ]
