# Generated by Django 5.2.3 on 2025-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='task_type',
            field=models.CharField(choices=[('chart_generation', 'Chart Generation'), ('interpretation', 'AI Interpretation'), ('ephemeris', 'Ephemeris Calculation'), ('plugin_processing', 'Plugin Processing')], help_text='Type of task', max_length=50),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['task_type', 'state'], name='chart_task__task_ty_dc4065_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['user', 'state'], name='chart_task__user_id_95d106_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['user', 'task_type'], name='chart_task__user_id_687b81_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['user', 'completed_at'], name='chart_task__user_id_ba1e06_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['created_at', 'state'], name='chart_task__created_779d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['started_at', 'state'], name='chart_task__started_12ef8e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['completed_at', 'state'], name='chart_task__complet_8de607_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['progress', 'state'], name='chart_task__progres_0ba8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['created_at', 'user'], name='chart_task__created_44a75d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['state', 'created_at'], name='chart_task__state_f44bf6_idx'),
        ),
    ]
